### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by mirco1000** [Shoety/cordova-plugin-inappbrowserxwalk#15]
hello, i'm trying to build my project it gives me this error

BUILD FAILED

Total time: 2.913 secs

C:\hello\platforms\android\cordova\node_modules\q\q.js:126
                    throw e;
                          ^
Error code 1 for command: cmd with args: /s /c "C:\hello\platforms\android\grad
lew cdvBuildDebug -b C:\hello\platforms\android\build.gradle -Dorg.gradle.daemo
n=true"
Error: C:\hello\platforms\android\cordova\build.bat: Command failed with exit c
ode 8
    at ChildProcess.whenDone (C:\Users\mark\AppData\Roaming\npm\node_modules\cor
dova\node_modules\cordova-lib\src\cordova\superspawn.js:135:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)

please help!

**Comment by mladenp** [comment]
Same problem, tried different android versions but nothing helps.

**Comment by bradrlaw** [comment]
See the pull request from mrjoes.  Its a one line change that fixes the build.

**Comment by mirco1000** [comment]
@bradrlaw  thanks for your help!
